// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Xz4YxJUhVQiSv-QWT1stp3A-HIiWRB4',
    appId: '1:494400810225:web:6589ad21bca5aeee59cd50',
    messagingSenderId: '494400810225',
    projectId: 'datlichkham-37558',
    authDomain: 'datlichkham-37558.firebaseapp.com',
    storageBucket: 'datlichkham-37558.firebasestorage.app',
    measurementId: 'G-0DZFNW3QNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARstkWBOTS_13VXp1gpA-ha1lFB3Ecwuo',
    appId: '1:494400810225:android:32b7927e429c827859cd50',
    messagingSenderId: '494400810225',
    projectId: 'datlichkham-37558',
    storageBucket: 'datlichkham-37558.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZZh1BUSTqsHDNfNycsnGgNSKOmNOxTEs',
    appId: '1:494400810225:ios:a06bfdf70b0d1de159cd50',
    messagingSenderId: '494400810225',
    projectId: 'datlichkham-37558',
    storageBucket: 'datlichkham-37558.firebasestorage.app',
    iosBundleId: 'com.example.qldatlich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZZh1BUSTqsHDNfNycsnGgNSKOmNOxTEs',
    appId: '1:494400810225:ios:a06bfdf70b0d1de159cd50',
    messagingSenderId: '494400810225',
    projectId: 'datlichkham-37558',
    storageBucket: 'datlichkham-37558.firebasestorage.app',
    iosBundleId: 'com.example.qldatlich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Xz4YxJUhVQiSv-QWT1stp3A-HIiWRB4',
    appId: '1:494400810225:web:72dd8b7b5991378b59cd50',
    messagingSenderId: '494400810225',
    projectId: 'datlichkham-37558',
    authDomain: 'datlichkham-37558.firebaseapp.com',
    storageBucket: 'datlichkham-37558.firebasestorage.app',
    measurementId: 'G-MTW74F4TRQ',
  );
}
